epg:
- id: test-provider
  url: http://stream1.example.com/epg.xml
  labels:
  - sk
  channels_map:
    <epg_channel_id>: <channel_id>

channels:
- id: jednotka
  name: Jednotka HD
  logo: https://i.imgur.com/aqVki9i.png
  labels:
  - News

streams:
- channel: jednotka
  url: http://stream1.example.com/1.m3u8
  labels: 
  - h264
  provider: <provider_id>
  catchup:
    mode: default
    source: http://stream1.example.com/1.m3u8?duration={duration}&start={utc}
    days: 7

packages:
- id: package1
  name: Package 1
  formats:
  - m3u8
  - enigma2
  # select specific channels (in given order)
  channels:
  - jednotka
  # select channels by labels (groups in given order, other labels are ignored)
  channel_labels:
  - News
  # select streams by labels
  streams:
  - h264
  # select epg by labels
  epg:
  - sk
  # if we host logos on our server, we can use this to prefix the logo url
  # and path.Base(<logo url>) will be appended to it
  logos: http://localhost/logos
  # providers that will be used - if they have relative urls, they will be prefixed with the base url
  providers:
    <provider_id>: <url>
