#!/bin/sh
cd "$(dirname "$0")"

docker run -it \
    --name "go4tv_dev" \
    --entrypoint="go" \
    --volume "${PWD}/../:/app" \
    go4tv_img "$@";

#
# commit changes to image
docker commit "go4tv_dev" "go4tv_img"

#
# remove contianer
docker rm "go4tv_dev"
